### ISSUE TITLE
你好不支持auto

### ISSUE THREAD

**Issue by crazypoo** [anonymity-du/DoubleSliderView-Objective-C#1]
你好不支持autolayout

**Comment by crazypoo** [comment]
你好不支持autolayout

**Comment by anonymity-du** [comment]
内部初始化的时候要用到frame，所以你在使用自动布局的时候，先用initWithFrame

**Comment by crazypoo** [comment]
你可以初始化界面.然后layoutifneed,然后就可以了都9012年了还这样设置,落伍了

**Comment by anonymity-du** [comment]
？？这么个控件你还用得到layoutifneed？

**Comment by crazypoo** [comment]
是在控件里面哦

**Comment by crazypoo** [comment]
反正你这个我自己改成autolayout的了,你看着要不要改吧

**Comment by anonymity-du** [comment]
你改了后用着好就行，我这个控件只是提供一个思路。我个人觉得内部用手动布局更好，不想导入三方库，也不想用苹果原生自动布局写

**Comment by crazypoo** [comment]
你欢喜囖,我上传之后,看看你能不能指向我的git的这个文件囖

**Comment by crazypoo** [comment]
https://github.com/crazypoo/PTools/blob/master/PooTools/DoubleSliderView.m

**Comment by crazypoo** [comment]
https://github.com/crazypoo/PTools/blob/master/PooTools/DoubleSliderView.m

**Comment by anonymity-du** [comment]
OK,已放至readme
